version: '3'
services:
  frontend:
    build:
      context: ./ventas
    ports:
      - "3000:3000"
    networks:
      - ivstore-network

  backend:
    build:
      context: ./primerAPI
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: primerapi
      DB_USERNAME: root
      DB_PASSWORD:

    networks:
      - ivstore-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: primerapi
    command: --bind-address=0.0.0.0
    ports:
      - "3306:3306"
    networks:
      - ivstore-network

networks:
  ivstore-network:
    driver: bridge
